accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),

]

blog/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^$', 'blog.views.index', name='index'),
    url(r'^category/(?P<pk>\d+)/$', 'blog.views.category_detail', name='category_detail'),
    url(r'^category/(?P<pk>\d+)/edit/$', 'blog.views.category_edit', name='category_edit'),
    url(r'^(?P<pk>\d+)/$', 'blog.views.shop_detail', name='shop_detail'),
    url(r'^(?P<pk>\d+)/edit/$', 'blog.views.shop_edit', name='shop_edit'),
    url(r'^(?P<shop_pk>\d+)/reviews/new/$', 'blog.views.review_new', name='review_new'),
    url(r'^(?P<shop_pk>\d+)/reviews/(?P<pk>\d+)/edit/$', 'blog.views.review_edit', name='review_edit'),
    url(r'^newcategory/$', 'blog.views.category_new', name='category_new'),
    url(r'^newshop/$', 'blog.views.shop_new', name='shop_new'),


]

final/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include("blog.urls",namespace="blog")),

    url(r'^accounts/', include('accounts.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.conf import settings


class Category(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
                return self.name

class Shop(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=40)
    address = models.CharField(max_length=500)
    description = models.TextField()
    photo1 = models.ImageField()
    photo2 = models.ImageField(null=True, blank=True)
    photo3 = models.ImageField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category)

    def __str__(self):
                return self.name

class Review(models.Model):
    shop = models.ForeignKey(Shop)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    comment = models.TextField()
    photo1 = models.ImageField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
                return self.pk

blog/forms.py
from django import forms
from .models import Category, Shop, Review

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = '__all__'


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comment', 'photo1']

accounts/views.py
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(settings.LOGIN_URL)
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup_form.html', {
        'form': form,
    })

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from .models import Category, Shop, Review
from .forms import CategoryForm, ShopForm, ReviewForm
from datetime import date
from django.core.urlresolvers import reverse


def index(request):
    category_list = Category.objects.all()
    recent_reviews = Review.objects.filter().order_by('-id')[:10][::-1]
    #최근10개
    return render(request, 'blog/index.html', {
        'category_list': category_list, 'recent_reviews': recent_reviews,
    })

def category_new(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            category = form.save()
            url = reverse('blog:category_detail', args=[category.pk])
            messages.success(request, '카테고리를 등록했습니다.')

            return redirect(url)
    else:
        form = CategoryForm()
    return render(request, 'blog/category_form.html', {
        'form': form,
    })

def category_edit(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            category = form.save()
            messages.success(request, '카테고리가 수정되었습니다.')
            return redirect('blog:category_detail', pk)
    else:
        form = CategoryForm(instance=category)
    return render(request, 'blog/category_form.html', {
        'form': form,
    })


def category_detail(request, pk):
    category = get_object_or_404(Category, pk=pk)
    return render(request, 'blog/category_detail.html', {
        'category': category,
    })



def shop_new(request):
    if request.method == 'POST':
        form = ShopForm(request.POST, request.FILES)
        if form.is_valid():
            shop = form.save()
            url = reverse('blog:shop_detail', args=[shop.pk])
            messages.success(request, '새로운 샵을 등록했습니다.')
            return redirect(url)
    else:
        form = ShopForm()
    return render(request, 'blog/shop_form.html', {
        'form': form,
    })

def shop_edit(request, pk):
    shop = get_object_or_404(Shop, pk=pk)
    if request.method == 'POST':
        form = ShopForm(request.POST, request.FILES, instance=shop)
        if form.is_valid():
            shop = form.save()
            messages.success(request, '샵이 수정되었습니다.')
            return redirect('blog:shop_detail', pk)
    else:
        form = ShopForm(instance=shop)
    return render(request, 'blog/shop_form.html', {
        'form': form,
    })


def shop_detail(request, pk):
    shop = get_object_or_404(Shop, pk=pk)
    return render(request, 'blog/shop_detail.html', {
        'shop': shop,
    })

@login_required
def review_new(request, shop_pk):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.shop = get_object_or_404(Shop, pk=shop_pk)
            review.user = request.user
            review.save()
            messages.success(request, '새로운 리뷰가 등록되었습니다.')
            return redirect('blog:shop_detail', shop_pk)
    else:
        form = ReviewForm()
    return render(request, 'blog/review_form.html', {
        'form': form,
    })


@login_required
def review_edit(request, shop_pk, pk):
    review = get_object_or_404(Review, pk=pk)

    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES, instance=review)
        if form.is_valid():
            review = form.save(commit=False)
            review.shop = get_object_or_404(Shop, pk=shop_pk)
            review.user = request.user
            review.save()
            messages.success(request, '댓글이 수정되었습니다.')
            return redirect('blog:shop_detail', shop_pk)
    else:
        form = ReviewForm(instance=review)
    return render(request, 'blog/review_form.html', {
        'form': form,
    })

accounts/templates/accounts/signup_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/base.html
<!doctype html>
<html>
<head>
<meta charset="utf8" />
<title>Carholic</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<style>
body {
    padding-top: 60px;
    padding-bottom: 30px;
}
</style>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Carholic</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url "blog:index" %}">Home</a></li>
            <li></li>
            <li></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                {{ message }}
                </div>
                {% endfor %}
                {% endif %}

                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>

blog/templates/blog/category_detail.html
{% extends "blog/base.html" %}

{% block content %}

{% for shop in category.shop_set.all %}

<div class="col-sm-4">
    <img src="{{ shop.photo1.url }}" style="max-width: 100%;" />
    <div class="caption">
        <a href="{% url "blog:shop_detail" shop.pk %}">
            {{ shop.name }}
        </a>
    </div>
</div>
{% endfor %}

<a href="{% url "blog:index" %}">
    목록으로
</a>
<a href="{% url "blog:category_edit" category.pk %}">
    수정
</a>

{% endblock %}

blog/templates/blog/category_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="row">
        {% for category in category_list %}
  <div class="row">
        <a href="{% url "blog:category_detail" category.pk %}">
          <h1> {{ category.name }} </h1>
        </a>

          <hr />
          {% for shop in category.shop_set.all %}

          <div class="col-sm-4">
              <img src="{{ shop.photo1.url }}" style="max-width: 100%;" />
              <div class="caption">
                  <a href="{% url "blog:shop_detail" shop.pk %}">
                      {{ shop.name }}
                  </a>
              </div>
          </div>
          {% endfor %}
        </div>
        {% endfor %}
    </div>
  <div class="row">
    <h1> 최근 다섯개 댓글 </h1>
    {% for reviews in recent_reviews %}
    {{ reviews.comment }}
   <img src="{{ reviews.photo.url }}" />
    <hr />
    {% endfor %}



  </div>


  <a href="{% url "blog:category_new" %}">
      새카테고리
  </a>

  <a href="{% url "blog:shop_new" %}">
      새샵
  </a>


{% endblock %}

blog/templates/blog/review_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/shop_detail.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>{{ shop.title }}</h1>

    {{ shop.created_at }}
    {{ shop.updated_at }}
    <hr/>

    <img src="{{ shop.photo1.url }}" />
    {% if shop.photo2 %}
    <img src="{{ shop.photo2.url }}" />
    {% endif %}
    {% if shop.photo3 %}
    <img src="{{ shop.photo3.url }}" />
    {% endif %}

    {{ shop.description|linebreaks }}

    <a href="{% url "blog:shop_edit" shop.pk %}">
        샵수정
    </a>


    <h3>리뷰</h3>
    <a href="{% url "blog:review_new" shop.pk %}" class="btn btn-primary btn-block">댓글 쓰기</a>
    <ul>
    {% for review in shop.review_set.all %}
    <li>
        {{ review.comment }}
        by {{ review.user }}
        {{ review.updated_at }}
        <a href="{% url "blog:review_edit" shop.pk review.pk %}">
            수정
        </a>
    </li>
    {% endfor %}
    </ul>

    <hr/>
    <a href="{% url "blog:index" %}" class="btn btn-default">샵 목록</a>
{% endblock %}

blog/templates/blog/shop_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>